<!DOCTYPE html>
<html>
  <head>
    <title>Build Lesson Plan</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <h1>Build Lesson Plan</h1>
    <a href="/index/user-profile">Back to Profile</a>
    <section>
    		<label>Search</label>
    		<input id="searchQuery" type="text" name="search_text" />
    		<input type="submit" value="Search" />
    	
    	<ul id="results">
    		<li>Result 1 <a href="#">Add to Plan</a></li>
    		<li>Result 2 <a href="#">Add to Plan</a></li>
    		<li>Result 3 <a href="#">Add to Plan</a></li>
    	</ul>
    </section>
    <section>
	    <form>
	    	<label>Lesson Plan Name</label>
	    	<input type="text" name="plan_name" value="" />
	    	<label>Description</label>
	    	<textarea name="description"></textarea>
	    	<label>Resources</label>
	    	<ul>
	    		<li>Resource One</li>
	    		<li>Resource Two</li>
	    		<li>Resource Three</li>
	    	</ul>
	    	<input type="submit" class="btn btn-block" value="Save" />
	    </form>
    </section>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/lib/underscore-min.js"></script>
    <script type="text/javascript" src="/js/lib/backbone-min.js"></script>	
    <script type="text/javascript" src="/js/models.js"></script>
    <script type="text/javascript" src="/js/templates.js"></script>
    <script type="text/javascript" src="/js/renderer.js"></script>
    <script type="text/javascript" src="/js/store.js"></script>
    <script type="text/javascript" src="/js/buildPlanPage.js"></script>
    
  </body>
</html>