<!DOCTYPE html>
<html>
  <head>
    <title>Build Lesson Plan</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
 	<?php echo $this->render('/elements/header.phtml'); ?>
    <section class="content center">
    	<h1>Build Lesson Plan</h1>
    	<a href="/index/user-profile">Back to Profile</a>
    		
    	
    	
    </section>
    <section class="content center">
	    	<label>Lesson Plan Name</label>
	    	<input type="text" name="plan_name" value="" />
	    	<label>Description</label>
	    	<textarea name="description"></textarea>
	    	<label>Resources</label>
    		<label>Search</label>
	    	<input id="searchQuery" type="text" name="search_text" />
	    	<ul id="results">
	    		
	    	</ul>
	    	<input type="submit" class="btn btn-block" value="Save" />
    </section>
    <footer></footer>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/models.js"></script>
    <script type="text/javascript" src="/js/templates.js"></script>
    <script type="text/javascript" src="/js/renderer.js"></script>
    <script type="text/javascript" src="/js/store.js"></script>
    <script type="text/javascript" src="/js/buildPlanPage.js"></script>
  </body>
</html>