<!DOCTYPE html>
<html>
  <head>
    <title>Reach It! The Teaching Planner</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <h1>Login</h1>
    <a href="/index/register">Register</a>
    <section>
	    <form action="/index/login" method="post">
	    	<label>Username</label>
	    	<input type="text" name="username" value="" />
	    	<label>Password</label>
	    	<input type="password" name="password" value="" />
	    	<input type="submit" class="btn btn-block" value="Login" />
	    </form>
    </section>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>