<!DOCTYPE html>
<html>
  <head>
    <title>Reach It! The Teaching Planner</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <h1>Hello, kids!</h1>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript" src="/js/lib/underscore-min.js"></script>
    <script type="text/javascript" src="/js/lib/backbone-min.js"></script>
        
    <script src="/js/models.js"></script>
    <script src="/js/templates.js"></script>
  </body>
</html>