<!DOCTYPE html>
<html>
  <head>
    <title>Reach It! The Teaching Planner</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
  	<?php echo $this->render('/elements/header.phtml'); ?>
    <section class="content center">
    	<h1>Register</h1>
    	<a href="/index/login">Back to login</a>
	    <form>
	    	<label>Username</label>
	    	<input type="text" name="username" value="" />
	    	<label>Password</label>
	    	<input type="password" name="password" value="" />
	    	<label>Email Address</label>
	    	<input type="text" name="email" value="" />
	    	<input type="submit" class="btn btn-block" value="Register" />
	    </form>
    </section>
    <footer></footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>