<!DOCTYPE html>
<html>
  <head>
    <title>Build Lesson Plan</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
  	<?php echo $this->render('/elements/header.phtml'); ?>
    <section class="content center">
    	<h1>Search Lesson Plans</h1>
    	<a href="/index/user-profile">Back to Profile</a>
    	<form>
    		<label>Search Lesson Plans</label>
    		<input type="text" name="search_text" />
    		<input type="submit" value="Search" />
    	</form>
    	<ul>
    		<li class="result-item">Lesson Plan 1 <a href="/index/view-plan">View More</a></li>
    		<li class="result-item">Lesson Plan 2 <a href="/index/view-plan">View More</a></li>
    		<li class="result-item">Lesson Plan 3 <a href="/index/view-plan">View More</a></li>
    	</ul>
    </section>
    <footer></footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>