<!DOCTYPE html>
<html>
  <head>
    <title>Reach It! The Teaching Planner</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
  	<?php echo $this->render('/elements/header.phtml'); ?>
  	<section class="content center">
  		<span class="flt-right"><a href="/index/edit-account">Allen Torres</a></span>
  	</section>
  	<section class="content center">
	    <h2>My Lesson Plans</h2>
	    <ul class="clearfix">
	    	<li class="rnd-cell">
	    		<div class="icon science-icon"></div>
	    		<h3 class="nomarg">Science Now</h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mbTop15">Description of science now.</p>
	    	</li>
	    	<li class="rnd-cell">
	    		<div class="icon math-icon"></div>
	    		<h3 class="nomarg">Math Now</h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mbTop15">Description of math now.</p>
	    	</li>
	    	<li class="rnd-cell">
	    		<div class="icon eng-icon"></div>
	    		<h3 class="nomarg">English Now</h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mbTop15">Description of english now.</p>
	    	</li>
	    	<li class="rnd-cell">
	    		<div class="icon ss-icon"></div>
	    		<h3 class="nomarg">Social Studies Now</h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mbTop15">Description of social studies now.</p>
	    	</li>
	    </ul>
    </section>
    <footer></footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>