<!DOCTYPE html>
<html>
  <head>
    <title>Reach It! The Teaching Planner</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
    <h1><a href="/index/edit-account">Allen Torres</a></h1>
    <h2>My Plans</h2>
    <a href="/index/build-plan">Build a Lesson Plan</a>
    <a href="/index/search-plans">Search Lesson Plans</a>
    <ul>
    	<li>Plan One</li>
    	<li>Plan Two</li>
    	<li>Plan Three</li>
    </ul>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>