<!DOCTYPE html>
<html>
  <head>
    <title>Reach It! The Teaching Planner</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
  	<?php echo $this->render('/elements/header.phtml'); ?>
  	<section class="content center">
  		<span class="flt-right"><a href="/index/edit-account">Allen Torres</a>&nbsp;<a class="down-arrow" href="#">56</a></span><div class="edit-icon flt-right"></div>
  	</section>
  	<section class="content center mb50">
	    <h2>My Lesson Plans</h2>
	    <ul class="clearfix">
	    	<li class="rnd-cell">
	    		<div class="icon science-icon"></div>
	    		<div class="grade grade-a-plus"></div>
	    		<h3 class="nomarg"><a href="/index/view-plan/id/12345">Science</a></h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mt15">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nisl erat. Duis dictum nisl nulla. Quisque fringilla bibendum dolor. Proin eget enim enim, a fringilla leo.</p>
	    	</li>
	    	<li class="rnd-cell">
	    		<div class="icon math-icon"></div>
	    		<div class="grade grade-b-minus"></div>
	    		<h3 class="nomarg"><a href="/index/view-plan/id/12345">Math</a></h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mt15">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nisl erat. Duis dictum nisl nulla. Quisque fringilla bibendum dolor. Proin eget enim enim, a fringilla leo.</p>
	    	</li>
	    	<li class="rnd-cell">
	    		<div class="icon eng-icon"></div>
	    		<div class="grade grade-c"></div>
	    		<h3 class="nomarg"><a href="/index/view-plan/id/12345">English</a></h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mt15">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nisl erat. Duis dictum nisl nulla. Quisque fringilla bibendum dolor. Proin eget enim enim, a fringilla leo.</p>
	    	</li>
	    	<li class="rnd-cell">
	    		<div class="icon ss-icon"></div>
	    		<div class="grade grade-b-plus"></div>
	    		<h3 class="nomarg"><a href="/index/view-plan/id/12345">Social Studies</a></h3>
	    		<p><span class="italic">Mrs. Teacher</span><span class="flt-right italic">9/14/2012</span></p>
	    		<p class="clearboth mt15">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eget nisl erat. Duis dictum nisl nulla. Quisque fringilla bibendum dolor. Proin eget enim enim, a fringilla leo..</p>
	    	</li>
	    </ul>
    </section>
    <footer></footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>