<!DOCTYPE html>
<html>
  <head>
    <title>View Resource Details</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
  	<?php echo $this->render('/elements/header.phtml'); ?>
  	<section class="content center">
  		<h2>Nova Science Now</h2>
  		<p>Rate this resource</p>
  		<select>
  			<option value="5">A+</option>
  			<option value="4">A</option>
  			<option value="3">B</option>
  			<option value="2">C</option>
  			<option value="1">D</option>
  			<option value="0">F</option>
  		</select>
  		<p>Resource description of text and stuff.</p>
  	</section>
  	<section class="content center">
  		<h2>Comments</h2>
  		<form>
  			<label>Add Comment</label>
  			<textarea name="comment"></textarea>
  		</form>
  		<ul>
  			<li>I love this resource!</li>
  			<li>I love this resource!</li>
  			<li>I love this resource!</li>
  		</ul>
  	</section>
  	<footer></footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>