<!DOCTYPE html>
<html>
  <head>
    <title>View Resource Details</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">
  </head>
  <body>
  	<?php echo $this->render('/elements/header.phtml'); ?>
  	<section class="content center">
  		<h2>Nova Science Now</h2>
  		<p>Rate this resource</p>
  		<select>
  			<option value="5">A+</option>
  			<option value="4">A</option>
  			<option value="3">B</option>
  			<option value="2">C</option>
  			<option value="1">D</option>
  			<option value="0">F</option>
  		</select>
  		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tristique nulla sit amet sem molestie nec dictum felis fermentum. Aenean rutrum tempor mauris, nec egestas ligula gravida vitae. Nulla pretium, tellus ullamcorper tincidunt mattis, augue nisl adipiscing lacus, in hendrerit magna nisl sit amet augue. Phasellus id leo libero. Nullam non erat non elit dictum consectetur ut ac ligula. Donec erat enim, ultrices non condimentum ac, tristique sed quam. Phasellus vel felis tortor. Nam metus turpis, aliquet et suscipit ut, posuere et velit. Vestibulum nisi diam, dictum condimentum dignissim in, interdum eu sem. Phasellus odio eros, iaculis non ultricies non, faucibus vitae erat. </p>
  	</section>
  	<section class="content center">
  		<h2>Comments</h2>
  		<form>
  			<textarea class="fullwidth h100" name="comment"></textarea>
  			<input type="submit" class="btn" value="Add" />
  		</form>
  		<h4>User Comments</h4>
  		<ul>
  			<li class="result-item">I love this resource!</li>
  			<li class="result-item">I love this resource!</li>
  			<li class="result-item">I love this resource!</li>
  		</ul>
  	</section>
  	<footer></footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>