<!DOCTYPE html>
<html>
  <head>
    <title>Build Lesson Plan</title>
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
  	<section>
  		<h1>Lesson Plan Name</h1>
  		<p>Rate this lesson plan</p>
  		<select>
  			<option value="5">A+</option>
  			<option value="4">A</option>
  			<option value="3">B</option>
  			<option value="2">C</option>
  			<option value="1">D</option>
  			<option value="0">F</option>
  		</select>
    	<p>This lesson plan covers the basics of everything.</p>
    	<ul>
    		<li>Resource 1 <a href="/index/view-resource">View More</a></li>
    		<li>Resource 2 <a href="/index/view-resource">View More</a></li>
    		<li>Resource 3 <a href="/index/view-resource">View More</a></li>
    	</ul>
  	</section>
  	<section>
  		<h2>Comments</h2>
  		<form>
  			<label>Add Comment</label>
  			<textarea name="comment"></textarea>
  		</form>
  		<ul>
  			<li>I love this plan!</li>
  			<li>I love this plan!</li>
  			<li>I love this plan!</li>
  		</ul>
  	</section>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script src="/boostrap/js/bootstrap.min.js"></script>
  </body>
</html>